{% set pre_relation = source('raw_sheets', 'training_12_pre') %}
{% set post_relation = source('raw_sheets', 'training_12_post') %}

{{ config(
    materialized='table',
    persist_docs={'relation': true, 'columns': true},
    quoting={'identifier': true},
    tags=["staging", "training_12", "training"]
) }}

-- `recursive` is required because name_groups (further down) is a recursive CTE;
-- in Postgres the keyword is declared once for the whole WITH chain.

with recursive
-- pre_base / post_base: one CTE per source form, generated by the Jinja loop.
-- Maps whatever column names each Google Form export happens to use onto a
-- fixed set of *_raw columns (via first_existing_column), casts everything to
-- text, tags rows with 'pre'/'post', and assigns an arbitrary per-source row id.
{% for form_tag, relation in {'pre': pre_relation, 'post': post_relation}.items() %}
{{ form_tag }}_base as (
    select
        row_number() over () as source_row_id,
        '{{ form_tag }}'::text as form_tag,
        cast({{ first_existing_column(relation, ['Nama', 'Nama lengkap', 'Nama Lengkap']) }} as text) as nama_raw,
        cast({{ first_existing_column(relation, ['Desa']) }} as text) as desa_raw,
        cast({{ first_existing_column(relation, ['Usia', 'Umur']) }} as text) as usia_raw,
        cast({{ first_existing_column(relation, ['Peran', 'Peran anda']) }} as text) as peran_raw,
        cast({{ first_existing_column(relation, ['Score']) }} as text) as score_raw,
        cast({{ first_existing_column(relation, ['Provinsi', 'Mohon Pilih Provinsi', 'Pilih Provinsi']) }} as text) as provinsi_raw,
        cast({{ first_existing_column(relation, ['Kabupaten', 'Pilih Nama Kabupaten']) }} as text) as kabupaten_raw,
        cast({{ first_existing_column(relation, ['Kecamatan']) }} as text) as kecamatan_raw,
        cast({{ first_existing_column(relation, ['Puskesmas', 'Puskesmas Pengampu', 'Puskesmas pengampu']) }} as text) as puskesmas_raw,
        cast({{ first_existing_column(relation, ['Timestamp']) }} as text) as timestamp_raw_text,
        cast({{ first_existing_column(relation, ['Nomor_HP_WA', 'Nomor HP/WA', 'Nomor HP/Whatsapp', 'Nomor Handhone/Whatsapp']) }} as text) as phone_raw,
        cast({{ first_existing_column(relation, ['Jenis_Kelamin', 'Jenis Kelamin', 'Jenis kelamin']) }} as text) as jenis_kelamin_raw,
        cast({{ first_existing_column(relation, ['NIK']) }} as text) as nik_raw,
        cast({{ first_existing_column(relation, ['Pendidikan_Terakhir', 'Pendidikan Terakhir', 'Pendidikan terakhir']) }} as text) as education_raw,
        cast({{ first_existing_column(relation, ['Posyandu', 'Nama Posyandu', 'Nama Posyandu Binaan', 'Asal Posyandu']) }} as text) as posyandu_raw
    from {{ relation }}
){% if not loop.last %},{% endif %}
{% endfor %},

-- all_rows: stack pre and post responses into a single table. Safe because both
-- base CTEs expose identical column names and types; form_tag tells them apart.
all_rows as (
    select * from pre_base
    union all
    select * from post_base
),

-- keyed (cleaning stage 1): blank strings -> null, trim whitespace, extract the
-- numeric age, parse the timestamp (handles both MM/DD/YYYY HH:MM:SS and ISO),
-- and compute every macro-derived matching key (normalized name/geo keys,
-- digits-only phone and NIK) exactly once. Later CTEs branch on these aliases
-- instead of re-invoking the macros.
keyed as (
    select
        concat(form_tag, '_', source_row_id) as record_id,
        form_tag,
        source_row_id,
        nullif(trim(nama_raw), '') as nama_raw,
        nullif(trim(desa_raw), '') as desa_raw,
        substring(nullif(trim(usia_raw), '') from '([0-9]+)') as usia,
        nullif(trim(peran_raw), '') as peran_raw,
        nullif(trim(provinsi_raw), '') as provinsi_raw,
        nullif(trim(kabupaten_raw), '') as kabupaten_raw,
        nullif(trim(kecamatan_raw), '') as kecamatan_raw,
        nullif(trim(puskesmas_raw), '') as puskesmas_raw,
        nullif(trim(phone_raw), '') as phone_raw,
        nullif(trim(jenis_kelamin_raw), '') as jenis_kelamin_raw,
        nullif(trim(nik_raw), '') as nik_raw,
        nullif(trim(education_raw), '') as education_raw,
        nullif(trim(posyandu_raw), '') as posyandu_raw,
        case
            when nullif(trim(timestamp_raw_text), '') is null then null
            when trim(timestamp_raw_text) ~ '^[0-9]{1,2}/[0-9]{1,2}/[0-9]{4} [0-9]{1,2}:[0-9]{2}:[0-9]{2}$'
                then cast(to_timestamp(trim(timestamp_raw_text), 'MM/DD/YYYY HH24:MI:SS') as timestamp)
            else cast(trim(timestamp_raw_text) as timestamp)
        end as timestamp_raw,
        nullif(regexp_replace(trim(score_raw), '[[:space:]]+', '', 'g'), '') as score_clean,
        {{ profile_name_key('nama_raw') }} as nama_key,
        {{ profile_name_key('desa_raw') }} as desa_key,
        {{ profile_name_key('kabupaten_raw') }} as kabupaten_key,
        {{ profile_name_key('kecamatan_raw') }} as kecamatan_key,
        {{ profile_name_key('puskesmas_raw') }} as puskesmas_key,
        {{ profile_name_key('jenis_kelamin_raw') }} as jenis_kelamin_key,
        {{ profile_name_key('education_raw') }} as education_key,
        {{ profile_name_key('peran_raw') }} as peran_key,
        {{ profile_whatsapp_key('phone_raw') }} as phone_digits,
        {{ profile_whatsapp_key('nik_raw') }} as nik_digits
    from all_rows
),

-- normalized (cleaning stage 2): derive standardized fields from the keys —
--   score:          "17/20" -> percentage (85), plain numbers rounded to int
--   phone_key:      canonical local format (62xxx -> 0xxx, ensure leading 0),
--                   null if under 8 digits
--   nik_key:        ID digits, kept only if plausibly long (>= 10)
--   jenis_kelamin:  gender normalized to laki_laki / perempuan
--   education:      free-text education mapped to 5 ordered buckets
--   peran_category: free-text role mapped to Health Worker / Community Health
--                   Worker / Task Force / General via keyword regexes
normalized as (
    select
        *,
        case
            when score_clean ~ '^[0-9]+(\.[0-9]+)?/[0-9]+(\.[0-9]+)?$'
                then cast(round(cast(split_part(score_clean, '/', 1) as numeric)
                     / nullif(cast(split_part(score_clean, '/', 2) as numeric), 0) * 100, 0) as integer)
            when score_clean ~ '^[0-9]+(\.[0-9]+)?$'
                then cast(round(cast(score_clean as numeric), 0) as integer)
        end as score,
        case
            when phone_digits is null or length(phone_digits) < 8 then null
            when phone_digits like '62%' then '0' || substr(phone_digits, 3)
            when phone_digits like '0%' then phone_digits
            else '0' || phone_digits
        end as phone_key,
        case when length(nik_digits) >= 10 then nik_digits end as nik_key,
        case
            when jenis_kelamin_key in ('laki laki', 'lakilaki') then 'laki_laki'
            when jenis_kelamin_key = 'perempuan' then 'perempuan'
        end as jenis_kelamin,
        case
            when education_key in ('tidak sekolah', 'tidak tamat sd', 'tidak tamat sd mi') then 'no_schooling'
            when education_key like 'sd%'
                or education_key in ('sekolah dasar sederajat', 'tamat sd mi', 'tamat sd sederajat') then 'primary'
            when education_key like 'smp%' or education_key like 'sltp%' then 'junior_secondary'
            when education_key like 'sma%' or education_key like 'slta%' then 'senior_secondary'
            when education_key ~ '(^| )(d1|d2|d3|d4|s1|s2|s3|diploma|sarjana|ners)( |$)' then 'higher_education'
        end as education,
        case
            when peran_key ~ '(bidan|perawat|gizi|tpg|tenaga kesehatan|nutrisionis|promkes|promosi kesehatan|pkb|plkb|sanitarian|pustu|kia)' then 'Health Worker'
            when peran_key ~ '(kader|kpm|dasawisma|daswisma|posyandu)' then 'Community Health Worker'
            when peran_key ~ '(^| )(tpk|pkk|sekdes|kepala desa|bpd|staf desa|perangkat desa|kasi)( |$)' then 'Task Force'
            else 'General'
        end as peran_category
    from keyed
),

-- name_observations: one row per distinct combination of name key + identifying
-- context (phone, NIK, geography). Input to the fuzzy-matching self-join below.
name_observations as (
    select distinct nama_key, phone_key, nik_key, desa_key, kabupaten_key, kecamatan_key, puskesmas_key
    from normalized
    where nama_key is not null
),

-- name_pairs: candidate "same person, name spelled differently" links.
-- Two different name keys are paired when they share hard evidence (same phone,
-- NIK, puskesmas, desa+kabupaten, or kecamatan+kabupaten) AND the names are
-- similar (trigram similarity >= 0.72, or one name is a prefix of the other,
-- e.g. "siti" vs "siti aminah"). root = the lexicographically smaller of the
-- pair, used as the group seed below.
name_pairs as (
    select distinct a.nama_key, least(a.nama_key, b.nama_key) as root
    from name_observations a
    join name_observations b
        on a.nama_key <> b.nama_key
        and (
            (a.phone_key is not null and a.phone_key = b.phone_key)
            or (a.nik_key is not null and a.nik_key = b.nik_key)
            or (a.puskesmas_key is not null and a.puskesmas_key = b.puskesmas_key)
            or (a.desa_key is not null and a.kabupaten_key is not null
                and a.desa_key = b.desa_key and a.kabupaten_key = b.kabupaten_key)
            or (a.kecamatan_key is not null and a.kabupaten_key is not null
                and a.kecamatan_key = b.kecamatan_key and a.kabupaten_key = b.kabupaten_key)
        )
        and (
            similarity(a.nama_key, b.nama_key) >= 0.72
            or a.nama_key like b.nama_key || ' %'
            or b.nama_key like a.nama_key || ' %'
        )
),

-- name_groups (recursive): transitive closure over the pairs, so chains link up
-- even without a direct match — if A~B and B~C, all three end up sharing a root.
-- The recursion runs to fixpoint, so no extra manual chaining hop is needed.
name_groups (nama_key, root) as (
    select nama_key, root from name_pairs
    union
    select np.nama_key, ng.root
    from name_pairs np
    join name_groups ng on np.root = ng.nama_key
),

-- name_group_map: collapse the closure to one label per name — the smallest
-- reachable root becomes the group id shared by every spelling variant.
name_group_map as (
    select nama_key, min(root) as name_group_key
    from name_groups
    group by nama_key
),

-- with_unified: pick one canonical display name per person group — the longest
-- raw spelling wins (ties broken by earliest timestamp, then record_id) and is
-- broadcast to every row in the group via first_value(). Singletons (names with
-- no match) need no special-case rows: the left join misses and the coalesce
-- falls back to nama_key / record_id, making each its own group.
with_unified as (
    select
        n.*,
        first_value(n.nama_raw) over (
            partition by coalesce(ngm.name_group_key, n.nama_key, n.record_id)
            order by length(coalesce(n.nama_raw, '')) desc, n.timestamp_raw asc nulls last, n.record_id
            rows between unbounded preceding and unbounded following
        ) as unified_name
    from normalized n
    left join name_group_map ngm on n.nama_key = ngm.nama_key
)

-- Final select: expose raw + cleaned + key columns, derive year and quarter
-- from the parsed timestamp, and drop internal helpers (score_clean,
-- phone_digits, *_key intermediates not listed here).
select
    record_id,
    form_tag,
    source_row_id,
    nama_raw,
    nullif(trim(unified_name), '') as unified_name,
    {{ profile_name_key('coalesce(unified_name, nama_raw)') }} as unified_name_key,
    desa_raw,
    usia,
    peran_raw,
    score,
    provinsi_raw,
    kabupaten_raw,
    kecamatan_raw,
    puskesmas_raw,
    posyandu_raw,
    timestamp_raw,
    case when timestamp_raw is not null then extract(year from timestamp_raw)::integer end as year,
    case when timestamp_raw is not null then concat(extract(year from timestamp_raw)::integer, '-Q', extract(quarter from timestamp_raw)::integer) end as quarter,
    phone_raw,
    phone_key,
    jenis_kelamin_raw,
    jenis_kelamin,
    nik_raw,
    nik_key,
    education_raw,
    education,
    peran_category,
    nama_key,
    desa_key,
    kabupaten_key,
    kecamatan_key,
    puskesmas_key
from with_unified