version: 2

sources:
  - name: raw_kobo
    schema: raw_kobo
    quoting:
      identifier: true
    tables:
      - name: ACTIVEAsesmen_Fungsionalitas_Kader_CHW_AIM
        identifier: ACTIVEAsesmen_Fungsionalitas_Kader_CHW_AIM