version: 2

sources:
  - name: raw_kobo
    schema: raw_kobo
    quoting:
      identifier: true
    tables:
      - name: ACTIVEAsesmen_Fungsionalitas_Kader_CHW_AIM
        identifier: ACTIVEAsesmen_Fungsionalitas_Kader_CHW_AIM
      - name: ACTIVEMonitoring_Posyandu
        identifier: ACTIVEMonitoring_Posyandu
  
  
  - name: raw_sheets
    schema: raw_sheets
    quoting:
      identifier: true
    tables:
      - name: 'ka_modul_01'
        identifier: 'ka_modul_01'
      - name: 'ka_modul_02'
        identifier: 'ka_modul_02'
      - name: 'ka_modul_03'
        identifier: 'ka_modul_03'
      - name: 'ka_past_quarter'
        identifier: 'ka_past_quarter'
      - name: 'training_01_participants'
        identifier: 'training_01_participants'
      - name: 'training_02_participants'
        identifier: 'training_02_participants'
      - name: 'training_03_participants'
        identifier: 'training_03_participants'
      - name: 'training_04_participants'
        identifier: 'training_04_participants'
      - name: 'training_05a_participants'
        identifier: 'training_05a_participants'
      - name: 'training_05b_participants'
        identifier: 'training_05b_participants'
      - name: 'training_06_participants'
        identifier: 'training_06_participants'
      - name: 'training_07_participants'
        identifier: 'training_07_participants'
      - name: 'training_09a_participants'
        identifier: 'training_09a_participants'
      - name: 'training_09b_participants'
        identifier: 'training_09b_participants'
      - name: 'training_10_participants'
        identifier: 'training_10_participants'
      - name: 'training_11_participants'
        identifier: 'training_11_participants'
      - name: 'training_12_pre'
        identifier: 'training_12_pre'
      - name: 'training_12_post'
        identifier: 'training_12_post'
      - name: 'register_posyandu_baduta'
        identifier: 'register_posyandu_baduta'
      - name: 'register_posyandu_bumil'
        identifier: 'register_posyandu_bumil'
